services:
  db:
    image: mysql:8.4.3
    ports: ["3308:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: distributech
    volumes:
      - db-data:/var/lib/mysql
      - ./bdd:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -uroot -pexample --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    ports: ["8080:8080"]
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on: [db]

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: distributech
      DB_PORT: "3306"
    command: ["tail","-f","/dev/null"]

volumes:
  db-data:
